import turtle
#tutle improted
bruh = 0
t = turtle.Turtle()
s = turtle.Screen()
turtle.speed(0)
# Head color
turtle.color("black", "blue")
turtle.begin_fill()
# Head
while bruh<4:
    turtle.forward(200)
    turtle.left(90)
    bruh += 1
turtle.end_fill()
#body
turtle.color('black', 'purple')
turtle.begin_fill()
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(424)
turtle.left(90)
#height
turtle.forward(200)
turtle.left(90)
#body length
turtle.forward(484)
turtle.left(90)
turtle.forward(140)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.end_fill()
# spikes
turtle.color("black", "green")
turtle.begin_fill()
turtle.left(45)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.end_fill()
turtle.left(45)
turtle.forward(200)
#LEG DAY
turtle.color("black", "orange")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(364)
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(484)
turtle.end_fill()
#also we realised there were shortcuts here ;(
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(424)
turtle.lt(90)
turtle.fd(80)
turtle.rt(90)
#SHADES
#SUNNY GANG
turtle.color("black", "black")
turtle.begin_fill()
turtle.fd(50)
turtle.rt(90)
turtle.fd(40)
turtle.lt(90)
turtle.fd(40)
turtle.lt(90)
turtle.fd(40)
turtle.rt(90)
turtle.fd(60)
turtle.rt(90)
turtle.fd(40)
turtle.lt(90)
turtle.fd(40)
turtle.lt(90)
turtle.fd(40)
turtle.rt(90)
turtle.fd(10)
turtle.lt(90)
turtle.fd(10)
turtle.lt(90)
turtle.fd(200)
turtle.lt(90)
turtle.fd(10)
turtle.end_fill()
s.exitonclick()